name: "Publish in nexus an existing release"
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
        run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
      - name: Generate list using Markdown
        run: |
          cat folder/folder.html >> $GITHUB_STEP_SUMMARY